name: BDS Build CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.5
    - name: Run distro.sh
      run: ./scripts/distro.sh ${{ matrix.os }}
      shell: bash
    - name: LL DISTRO
      run: ls -al distro
    - name: Upload linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: ./distro/bds_${{ matrix.os }}.tar.gz
