name: BDS Build CI

on: [push]

jobs:
  build-zzz:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.5
    - name: Run distro.sh
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/distro.sh
        ls -al ./distro/
      shell: bash
    - name: Copy binary
      run: cp $GITHUB_WORKSPACE/distro/bds_Linux.tgz ./bds-linux.tar.gz
    - name: Upload linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-linux
        path: |
          bds-linux.tar.gz