name: BDS Build CI

on: [push]

jobs:
  build-zzz:
    runs-on: ubuntu-latest
    steps:
    - name: Only do this when tagged
      run: echo "Hello tag ${{ github.ref }}"
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.5
    - name: Run distro.sh
      run: ./scripts/distro.sh
