name: BDS Build CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          name: linux
        - os: macos-latest
          name: macos
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.5
      - name: Run distro.sh
        run: ./scripts/distro.sh ${{ matrix.name }}
        shell: bash
      - name: Upload ${{ matrix.name }} artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary-${{ matrix.name }}
          path: ./distro/bds_${{ matrix.name }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/download-artifact@v2
        with:
          name: binary-linux
          path: .
      - uses: actions/download-artifact@v2
        with:
          name: binary-macos
          path: .
      - run: |
          echo ${{ github.sha }} > release.txt
      - name: List Files
        run: |
          ls -laht
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release.txt
            bds_linux.tar.gz
            bds_macos.tar.gz
